example/api/urls.py
from django.views.decorators.csrf import csrf_exempt
from django.conf.urls import url
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'ObjectAdd/$', csrf_exempt(views.addobject)),
    re_path(r'ObjectView/$', views.getobject),
]

example/urls.py
from django.conf.urls import url
from example import views

# SET THE NAMESPACE
app_name = 'example'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^add_object/$',views.add_object,name='add_object'),
]

task/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from example import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^example/',include('example.urls')),
    url(r'^search/', include('search.urls'),name="search"),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^api/example/', include('example.api.urls'))
]

example/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username


class Object(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    activated = models.BooleanField(default=False)
    slug = models.SlugField(null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default = None)

    class Meta:
        indexes = [
            models.Index(fields=['name', 'description'])
        ]
    def __str__(self):
        return self.name

example/forms.py
from django import forms
from django.core.exceptions import ValidationError
from example.models import UserProfileInfo, Object
from django.contrib.auth.models import User

def ForbiddenUsernamesValidator(value):
    forbidden_usernames = ['admin', 'settings', 'news', 'about', 'help', 'signin', 'signup',
        'signout', 'terms', 'privacy', 'cookie', 'new', 'login', 'logout', 'administrator',
        'join', 'account', 'username', 'root', 'blog', 'user', 'users', 'billing', 'subscribe',
        'reviews', 'review', 'blog', 'blogs', 'edit', 'mail', 'email', 'home', 'job', 'jobs',
        'contribute', 'newsletter', 'shop', 'profile', 'register', 'auth', 'authentication',
        'campaign', 'config', 'delete', 'remove', 'forum', 'forums', 'download', 'downloads',
        'contact', 'blogs', 'feed', 'feeds', 'faq', 'intranet', 'log', 'registration', 'search',
        'explore', 'rss', 'support', 'status', 'static', 'media', 'setting', 'css', 'js',
        'follow', 'activity', 'questions', 'network',]
    if value.lower() in forbidden_usernames:
        raise ValidationError('This is a reserved word.')


def InvalidUsernameValidator(value):
    if '+' in value or '-' in value:
        raise ValidationError('Enter a valid username.')


def UniqueEmailValidator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')


def UniqueUsernameIgnoreCaseValidator(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')


class UserForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),
        max_length=30,
        required=True,
        label='User Name')

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}),
        max_length=100,
        required=True,
        label='Email')

    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'password', 'email']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(ForbiddenUsernamesValidator)
        self.fields['username'].validators.append(InvalidUsernameValidator)
        self.fields['username'].validators.append(UniqueUsernameIgnoreCaseValidator)

    def clean(self):
        super(UserForm, self).clean()
        password = self.cleaned_data.get('password')
        return self.cleaned_data


class UserProfileInfoForm(forms.ModelForm):
     portfolio_site = forms.URLField(initial="http://",widget=forms.TextInput(attrs={'class':'form-control'}),
     max_length=250,
     required=True,
     label='Portfolio Site')

     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')


class ObjectForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),
        max_length=30,
        required=True,
        label='Name')

    description = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),
        max_length=300,
        required=True,
        label='Description')

    activated = forms.BooleanField(required=False,initial=False,label='Activated')

    class Meta():
         model = Object
         fields = ('name','description', 'activated', 'slug')

example/api/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from exceptionlog import utils
from example.models import *
import json

def addobject(request):
    res = {}
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            rc = Object()
            rc.name = data['name']
            rc.description = data['description']
            rc.slug = data['slug']
            rc.user = User.objects.get(pk=int(data['id']))
            rc.save()
            res['status']=1
        except:
            utils.PutException()
            res['status'] = 0
        return JsonResponse(res)

def getobject(request):
    res={}
    try:
        rec=Object.objects.all()
        mlist=[]
        for i in rec:
            temp={}
            temp['name']=i.name
            temp['date']=utils.formalDateWithTime(i.date)
            temp['description']=i.description
            temp['activated']=i.activated
            temp['slug']=i.slug
            mlist.append(temp)
        res['status']=1
        res['data']=mlist
    except:
        utils.PutException()
        res['status'] = 0
    return JsonResponse(res)

example/views.py
from django.shortcuts import render
from example.forms import UserForm,UserProfileInfoForm, ObjectForm
from django.views.decorators.cache import cache_page
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from example.models import Object

def index(request):
    return render(request,'example/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'example/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                request.session['username'] = username
                request.session.set_expiry(8640)
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'example/login.html', {})

@login_required
def add_object(request):
    registered = False
    if request.method == 'POST':
        object_form = ObjectForm(data=request.POST)
        if object_form.is_valid():
            print(object_form)
            object = object_form.save(commit=False)
            object.user = request.user
            object.save()
            registered = True
            request.session.set_expiry(864)
        else:
            print(object_form.errors)
    else:
        object_form = ObjectForm()
    return render(request,'example/add_object.html',
                          {'object_form':object_form, 'registered': registered,
                          'objects': Object.objects.all().filter(user=request.user)})

templates/example/add_object.html
{% extends "example/base.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering new object!</h1>
      {% else %}
        <h1>Register Object Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ object_form.as_p }}
          <input type="submit" name="" value="Register Object">
        </form>

      {% endif %}
        <h3>List of home Objects</h3>
      <ul>
        {% for object in objects %}
           <li>
               {{ object }}{% if not forloop.last %},{% endif %}
            </li>
        {% endfor %}
        </ul>

    </div>
  </div>
{% endblock %}

templates/example/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'example:add_object' %}">Add object</a></li>
            {% if not hide_search %}
                <form class="navbar-form navbar-left" role="search" action="{% url 'searchposts' %}">
                  <div class="input-group" style="width:350px;">
                    <input type="text" class="form-control" name="q" placeholder="Find questions">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-default">Find</span></button>
                    </span>
                  </div>
                </form>
              {% endif %}
          {% else %}
            <li><a class="navbar-link" href="{% url 'example:user_login' %}">Login</a></li>
            <li><a class="navbar-link" href="{% url 'example:register' %}">Register</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/example/base1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          {# Django Home Link #}
          <li><a class="navbar-brand" href="{% url 'index' %}">TASK</a></li>
          {# Some logic on what to display for last item#}
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/example/base2.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
#mySidenav a {
  position: absolute;
  left: -80px;
  transition: 0.3s;
  padding: 15px;
  width: 100px;
  text-decoration: none;
  font-size: 20px;
  color: white;
  border-radius: 0 5px 5px 0;
}

#mySidenav a:hover {
  left: 0;
}

#about {
  top: 20px;
  background-color: #2196F3;
}

</style>
</head>
<body>

<div id="mySidenav" class="sidenav">
  <a href="{% url 'index' %}" id="about">Home</a>
</div>
<div class="container">
{% block body_block %}
{% endblock %}
</div>
</body>
</html>

templates/example/index.html
{% extends "example/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the HOME !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/example/login.html
{% extends "example/base2.html" %}
{% block body_block %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-50 p-b-90">
				<form method="post" action="{% url 'example:user_login' %}" class="login100-form validate-form flex-sb flex-w" id="login-form">
          {% csrf_token %}
					<span class="login100-form-title p-b-51">
						Login
					</span>


					<div class="wrap-input100 validate-input m-b-16" data-validate = "Username is required">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>


					<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn m-t-17">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>

	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>

	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>

	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>

	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>

	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>

	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>
{% endblock %}

templates/example/registration.html
{% extends "example/base2.html" %}
{% load crispy_forms_tags %}
{% crispy form %}
{% load staticfiles %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Registration</title>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
    <div class="limiter">
      <div class="container-login100">
        <div class="wrap-login100 p-t-50 p-b-90">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <span class="login100-form-title p-b-51">
          Register Here
        </span>
       <form enctype="multipart/form-data" method="POST" class="login100-form validate-form flex-sb flex-w">
          {% csrf_token %}
          {{ user_form|crispy }}
          {{ profile_form|crispy }}

          <div class="container-login100-form-btn m-t-17">
            <button class="login100-form-btn">
              Register
            </button>
          </div>
        </form>
      {% endif %}
  </div>
    </div>
      </div>
        </div>
        <div id="dropDownSelect1"></div>

      	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>

      	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>

      	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>

      	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

      	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>

      	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>

      	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>

      	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>

      	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>
{% endblock %}